{% set name = "bewegung" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bewegung-{{ version }}.tar.gz
  sha256: 5b6643e6ddce761cf9d65301614bd59c62d8f10868934e4442b67b992e549479

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - datashader
    - ffmpeg
    - ipython
    - matplotlib-base
    - librsvg
    - numba
    - numpy
    - pango
    - pillow
    - pycairo
    - pygobject
    - python >=3.6
    - tqdm
    - typeguard

test:
  imports:
    - bewegung
    - bewegung.core.backends.drawingboard.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pleiszenburg/bewegung
  summary: a versatile video renderer
  license: LGPL-2.1-or-later
  license_file: LICENSE
  doc_url: https://bewegung.readthedocs.io/
  dev_url: https://github.com/pleiszenburg/bewegung

extra:
  recipe-maintainers:
    - s-m-e
